
async function loadChat() {
  const params = new URLSearchParams(window.location.search);
  const chatId = params.get("chatId");
  if (!chatId) return;

  const res = await fetch(`http://localhost:3000/api/chat/${chatId}`);
  const chat = await res.json();

  document.getElementById("chat-title").innerText = chat.title;

  // const container = document.getElementById("chat-container");
  const container = document.getElementById("messages");

  container.innerHTML = "";

  chat.messages.forEach((msg, index) => {
  const isLastUserMessage =
    msg.role === "user" &&
    index === chat.messages.length - 2; 
  if (isLastUserMessage) return;

  if (msg.role === "user") {
    const q = document.createElement("div");
    q.className = "question-text";
    q.innerText = msg.content;
    container.appendChild(q);
  }

  if (msg.role === "assistant") {
    const label = document.createElement("div");
    label.className = "answer-toolbar";
    label.innerText = `Answer generated by ${msg.model || "model"}`;

    const a = document.createElement("div");
    a.className = "message assistant";
    a.innerText = msg.content;

    container.appendChild(label);
    container.appendChild(a);
  }
});

  container.scrollTop = container.scrollHeight;
}


async function loadSidebar() {
  const res = await fetch("http://localhost:3000/api/chats");
  const chats = await res.json();

  const list = document.querySelector(".chat-list");
  list.innerHTML = "";

  chats.forEach(chat => {
    const li = document.createElement("li");
    li.innerText = chat.title;

    const params = new URLSearchParams(window.location.search);
    if (params.get("chatId") === chat._id) {
      li.classList.add("active-chat");
    }

    li.onclick = () => {
      window.location.href = `screen2.html?chatId=${chat._id}`;
    };

    list.appendChild(li);
  });
}

async function sendMessage() {
  const input = document.getElementById("prompt");
  const message = input.value.trim();
  if (!message) return;

  const params = new URLSearchParams(window.location.search);
  const chatId = params.get("chatId");
  const model = document.getElementById("model").value;

  input.value = "";

  await fetch("http://localhost:3000/api/chat", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      chatId,
      message,
      model
    })
  });

  loadChat();
}

document.addEventListener("DOMContentLoaded", () => {
  loadChat();
  loadSidebar();

  const input = document.getElementById("prompt");
  input.addEventListener("keydown", e => {
    if (e.key === "Enter") {
      sendMessage();
    }
  });
});

